---
# handlers file for swap

- name: Allocate space for swap file
  ansible.builtin.command:
    cmd: "fallocate -l {{ swap_size }}M {{ swap_path }}"
  when: swap_file_created.changed
  changed_when: true

- name: Make swap file
  ansible.builtin.command:
    cmd: "mkswap {{ swap_path }}"
  when: swap_file_created.changed
  changed_when: true

- name: Enable swap file
  ansible.builtin.command:
    cmd: "swapon {{ swap_path }}"
  when: swap_file_created.changed
  changed_when: true

- name: Set swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
