---
# tasks file for roles/compose

- name: Create directories for containers
  ansible.builtin.file:
    path: "{{ compose_root_dir }}/{{ item.path }}"
    state: "{{ item.state }}"
    mode: "{{ item.mode }}"
    owner: "{{ item.owner | default(ansible_user) }}"
    group: "{{ item.group | default(ansible_user) }}"
  loop:
    - { path: "compose", state: "directory", mode: "775" }
    - { path: "compose/{{ ansible_hostname }}", state: "directory", mode: "775" }
    - { path: "appdata", state: "directory", mode: "775" }
    - { path: "logs", state: "directory", mode: "775" }
    - { path: "scripts", state: "directory", mode: "775" }
    - { path: "secrets", state: "directory", mode: "600", owner: "root", group: "root" }
    - { path: "shared", state: "directory", mode: "775" }

- name: Copy .env file to server
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../roles/compose/templates/.env.j2"
    dest: "{{ compose_root_dir }}/.env"
    mode: "600"
    owner: "root"
    group: "root"

- name: Set containers ACL for ansible_user and docker
  ansible.builtin.include_tasks: setacl.yml

- name: Container Lifecycle Management
  ansible.builtin.include_tasks: manage.yml
  when: compose_apps is defined and compose_apps is not none
