---
- name: Generate Reality keypair locally
  ansible.builtin.command: "sing-box generate reality-keypair"
  register: reality_keypair
  changed_when: false
  delegate_to: localhost

- name: Set Reality private key
  ansible.builtin.set_fact:
    reality_private_key: "{{ reality_keypair.stdout_lines[0].split(':')[1] | trim }}"
  delegate_to: localhost

- name: Set Reality public key
  ansible.builtin.set_fact:
    reality_public_key: "{{ reality_keypair.stdout_lines[1].split(':')[1] | trim }}"
  delegate_to: localhost

- name: Generate Reality short ID locally
  ansible.builtin.command: "sing-box generate rand 8 --hex"
  register: reality_short_id
  changed_when: false
  delegate_to: localhost

- name: Set Reality short ID
  ansible.builtin.set_fact:
    reality_short_id: "{{ reality_short_id.stdout | trim }}"
  delegate_to: localhost

- name: Generate Reality UUID locally
  ansible.builtin.command: "sing-box generate uuid"
  register: reality_uuid
  changed_when: false
  delegate_to: localhost

- name: Set Reality UUID
  ansible.builtin.set_fact:
    reality_uuid: "{{ reality_uuid.stdout | trim }}"
  delegate_to: localhost

- name: Save generated variables to a file locally
  ansible.builtin.copy:
    content: |
      Private Key: {{ reality_private_key }}
      Public Key: {{ reality_public_key }}
      Short ID: {{ reality_short_id }}
      UUID: {{ reality_uuid }}
    dest: "/tmp/reality_keys_info.txt"
    mode: "0644"
  delegate_to: localhost

- name: Configure the server with reality keys and UUID locally
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../roles/compose/templates/sing-box_config.j2"
    dest: "/tmp/config.json" # 临时生成配置文件
    mode: "0644" # 设置文件权限
  vars:
    compose_user_name: "jamesflare"
    compose_user_uuid: "{{ reality_uuid }}"
    compose_tls_server_name: "portfolio.newschool.edu"
    compose_tls_handshake_server: "portfolio.newschool.edu"
    compose_tls_handshake_server_port: 443
    compose_tls_private_key: "{{ reality_private_key }}"
    compose_tls_short_id: ["{{ reality_short_id }}"]
  delegate_to: localhost

- name: Upload the generated config to remote server
  ansible.builtin.copy:
    src: "/tmp/config.json"
    dest: "{{ compose_user_dir }}/{{ compose_root_dir }}/appdata/sing-box"
    owner: root
    group: root
    mode: "0644"

- name: Restart sing-box container using Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ compose_root_dir }}" # 根据路径调整
    state: restarted
  become: true
  when: compose_apps is defined and 'sing-box' in compose_apps
