---
- name: Check if swap is active
  ansible.builtin.command: swapon --show
  register: swap_status
  changed_when: false # If swap is not enabled, this task will not be marked as changed
  failed_when: false


# 禁用 swap 并删除 swap 文件
- name: Disable swap and remove swap file if it exists
  block:
    - name: Disable swap file
      ansible.builtin.command: swapoff -a
      when: swap_status.stdout | length > 0  # 只有启用了 swap 才执行
      changed_when: true

    - name: Remove swap file if it exists
      ansible.builtin.file:
        path: "{{ swap_path }}"
        state: absent
