---
- name: Test compose role
  hosts: cloud
  roles:
    - role: compose
      vars:
        compose_root_dir: /home/ubuntu/containers
        compose_proxy_enable: true
        compose_traefik_enable: false
        compose_apps:
          - name: portainer
            state: present
            rm_conf: false
          - name: sing-box
            state: present
            rm_conf: false
    - role: sing-box-gen
      vars:
        sing_box_log: false
        sing_box_log_level: "info"
        sing_box_ss_enable: true
        sing_box_vless_enable: true
        sing_box_vmess_enable: true
        sing_box_hysteria2_enable: false
        sing_box_tuic_enable: false
        # sing_box_ss_users:
        #   - name: "user1"
        multiplex_enable: true
        multiplex_padding: true
        brutal_enable: false
        # Add other necessary variables here
