---
- name: Test compose role
  hosts: localhost
  roles:
    - role: compose
      vars:
        compose_root_dir: /home/ubuntu/containers
        compose_proxy_enable: true
        compose_traefik_enable: false
        compose_apps:
          # - sing-box
          - portainer
          # - semaphore
