---
- name: Test compose role
  hosts: localvm
  roles:
    - role: compose
      vars:
        compose_root_dir: /home/ubuntu/containers
        compose_proxy_enable: true
        compose_traefik_enable: false
        compose_apps:
          - name: portainer
            state: absent
            rm_conf: true
          - name: sing-box
            state: absent
            rm_conf: true
          - name: qbittorrent
            state: absent
            rm_conf: true

