services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    profiles: ["apps", "core", "all"]
    networks:
      - nproxy
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $APPDATA/portainer:/data