services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    profiles: ["apps", "proxy", "all"]
    restart: always
    network_mode: host
    volumes:
      - $APPDATA/sing-box/:/etc/sing-box/
    command: -D /var/lib/sing-box -C /etc/sing-box/ run